<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
    <ProjectReference Include="..\..\src\Laya.Core\Laya.Core.csproj" />
    <Compile Include="..\..\src\Shared\Configuration\LayaProfileResolver.cs" Link="Shared\Configuration\LayaProfileResolver.cs" />
  </ItemGroup>

</Project>
