<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Laya.Core\Laya.Core.csproj" />
    <Compile Include="..\Shared\Configuration\LayaProfileResolver.cs" Link="Shared\Configuration\LayaProfileResolver.cs" />
  </ItemGroup>

</Project>
